---
version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "daily"
    labels:
      - "C-dependency"
    assignees:
      - "jdno"
    reviewers:
      - "jdno"
