---
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/languages/node"
    schedule:
      interval: "daily"
    labels:
      - "C-dependency"
    assignees:
      - "jdno"
    reviewers:
      - "jdno"

  - package-ecosystem: "cargo"
    directory: "/languages/rust"
    schedule:
      interval: "daily"
    labels:
      - "C-dependency"
    assignees:
      - "jdno"
    reviewers:
      - "jdno"

  - package-ecosystem: "cargo"
    directory: "/test-server"
    schedule:
      interval: "daily"
    labels:
      - "C-dependency"
    assignees:
      - "jdno"
    reviewers:
      - "jdno"
