[package]
name = "test-server"
version = "0.1.1"
authors = ["Jan David <jandavid@playlunaria.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunaria-api = { path = "../languages/rust", version = "0.1.1", features = ["server"] }

tokio = { version = "1.4.0", features = ["full"] }
tokio-compat-02 = "0.2.0"
tonic = "0.4.1"
