---
name: Node

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: languages/node

      - name: Lint project
        working-directory: languages/node
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.6
        with:
          path: |
            test-server/.cargo/registry
            test-server/.cargo/git
            test-server/target
          key: ${{ runner.os }}-stable-cargo-v1-${{ hashFiles('test-server/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-stable-cargo-v1-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build test server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path test-server/Cargo.toml

      - name: Set up Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: languages/node

      - name: Build Node client
        working-directory: languages/node
        run: yarn build

      - name: Run tests
        run: bin/test-node

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: prettier
        uses: creyD/prettier_action@v4.0
        with:
          dry: true
          prettier_options: "--check **.{js,json,ts}"
