---
name: Protobuf

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v0.3.1

      - name: Run Buf
        uses: bufbuild/buf-lint-action@v0.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: protobufs
