---
name: Rust

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.6
        with:
          path: |
            languages/rust/.cargo/registry
            languages/rust/.cargo/git
            languages/rust/target
            test-server/.cargo/registry
            test-server/.cargo/git
            test-server/target
          key: ${{ runner.os }}-stable-cargo-v1-${{ hashFiles('languages/rust/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-stable-cargo-v1-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path languages/rust/Cargo.toml --all-targets --all-features -- -D warnings

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path languages/rust/Cargo.toml --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      LUNARIA_ADDRESS: 127.0.0.1:1904

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.6
        with:
          path: |
            languages/rust/.cargo/registry
            languages/rust/.cargo/git
            languages/rust/target
            test-server/.cargo/registry
            test-server/.cargo/git
            test-server/target
          key: ${{ runner.os }}-stable-cargo-v1-${{ hashFiles('test-server/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-stable-cargo-v1-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build test server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path test-server/Cargo.toml

      - name: Build crate
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path languages/rust/Cargo.toml

      - name: Run tests
        run: bin/test-rust
